services:
  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ems_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./ems-backend
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_URL: jdbc:mysql://mysql:3306/ems_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./ems-frontend
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  mysql_data:
    name: companyproject_mysql_data
    external: true
