services:
  backend:
    build:
      context: ./ems-backend
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      DB_URL: jdbc:mysql://mysql:3306/ems_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "8082:8082"

    networks:
      - ems-network

  frontend:
    build:
      context: ./ems-frontend
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - ems-network

networks:
  ems-network:
    external: true
    name: companyproject_default
